description: Including production and integration environments
mailboxes:
  mailbox-ops:
    description: Mailbox for system notifications
    folders:
      inbox:
        description: default folder
        alert-regex: /(Error|Failure)/
      backup:
        description: messages from integration environment
        alert-regex: /(Error)/
        max-age: 1
      monitoring:
        description: icinga notifications
        alert-regex: /(Error|Failure)/
